import Foundation

/// Writes GitHub-browseable markdown for the W3C conformance suite.
///
/// Image links are relative paths into committed snapshot and W3C reference
/// PNGs — GitHub's markdown renderer will load them in the repo browser.
/// Do not copy pixels into `docs/`; regenerate these files after a full
/// conformance run via `swift run CoverageReport`.
public enum SVGConformanceMarkdownReport {

    public static let generatedMarker = "<!-- Generated by SVGConformanceMarkdownReport. Do not edit. -->"

    public static let indexFileName = "README.md"

    public static let thumbnailWidth = 240

    /// Reads `conformance-report.json` and writes the gallery beside it.
    public static func write(
        fromReportJSON reportURL: URL,
        repoRoot: URL,
        generatedOn: String? = nil,
        fileManager: FileManager = .default
    ) throws {
        let data = try Data(contentsOf: reportURL)
        let records = try JSONDecoder().decode([SVGConformanceRecord].self, from: data)
        try write(
            records,
            repoRoot: repoRoot,
            outputDirectory: reportURL.deletingLastPathComponent(),
            generatedOn: generatedOn,
            fileManager: fileManager
        )
    }

    /// Writes `README.md` plus one chapter file per feature tag.
    public static func write(
        _ records: [SVGConformanceRecord],
        repoRoot: URL,
        outputDirectory: URL,
        generatedOn: String? = nil,
        fileManager: FileManager = .default
    ) throws {
        try fileManager.createDirectory(at: outputDirectory, withIntermediateDirectories: true)

        let day = generatedOn ?? utcDayStamp(Date())
        let grouped = Dictionary(grouping: records, by: \.tag)
        let tags = sortedTags(Array(grouped.keys))
        let totals = StatusCounts(records)

        var written: Set<String> = [indexFileName]
        let index = indexMarkdown(tags: tags, grouped: grouped, totals: totals, generatedOn: day)
        try index.write(
            to: outputDirectory.appendingPathComponent(indexFileName),
            atomically: true,
            encoding: .utf8
        )

        for tag in tags {
            let chapterRecords = (grouped[tag] ?? []).sorted { $0.testId < $1.testId }
            let fileName = chapterFileName(for: tag)
            written.insert(fileName)
            let body = chapterMarkdown(
                tag: tag,
                records: chapterRecords,
                repoRoot: repoRoot,
                generatedOn: day,
                fileManager: fileManager
            )
            try body.write(
                to: outputDirectory.appendingPathComponent(fileName),
                atomically: true,
                encoding: .utf8
            )
        }

        try removeStaleGeneratedFiles(
            in: outputDirectory,
            keeping: written,
            fileManager: fileManager
        )
    }

    // MARK: - Index

    static func indexMarkdown(
        tags: [String],
        grouped: [String: [SVGConformanceRecord]],
        totals: StatusCounts,
        generatedOn: String
    ) -> String {
        var md = ""
        md += generatedMarker + "\n\n"
        md += "# Conformance coverage\n\n"
        md += "SVGeeKit vs. the vendored W3C SVG 1.1 Second Edition test suite. "
        md += "Each chapter page shows our committed render next to the W3C reference PNG.\n\n"
        md += "Generated from [`conformance-report.json`](conformance-report.json) on \(generatedOn). "
        md += "Regenerate with `swift run CoverageReport` after a full conformance run. Do not hand-edit.\n\n"

        md += "## Totals (\(totals.total) tests)\n\n"
        md += statusTable(totals)
        md += "\n"
        md += statusLegend()
        md += "\n\n"

        md += "## Chapters\n\n"
        md += "| Chapter | Tests | Passed | Partial | Skipped | Other |\n"
        md += "| --- | ---: | ---: | ---: | ---: | ---: |\n"
        for tag in tags {
            let counts = StatusCounts(grouped[tag] ?? [])
            let file = chapterFileName(for: tag)
            md += "| [\(tag)](\(file)) | \(counts.total) | \(counts.passed) | \(counts.partialBaseline) | \(counts.skipped) | \(counts.other) |\n"
        }
        md += "\n"

        md += "## Images\n\n"
        md += "Thumbnails are relative links into committed files — they load in GitHub's markdown viewer:\n\n"
        md += "- **SVGeeKit** — `Tests/__Snapshots__/<id>/baseline.png` when `passed` (verified), "
        md += "or `Tests/__PartialSnapshots__/<id>/baseline.png` when `partialBaseline` (unverified).\n"
        md += "- **W3C reference** — `Tests/SVGConformanceTests/Resources/W3C-SVG-1.1/png/<id>.png`.\n"
        md += "- Skipped tests and parse/render errors have no SVGeeKit snapshot.\n"
        return md
    }

    // MARK: - Chapter

    static func chapterMarkdown(
        tag: String,
        records: [SVGConformanceRecord],
        repoRoot: URL,
        generatedOn: String,
        fileManager: FileManager
    ) -> String {
        let counts = StatusCounts(records)
        var gallery: [SVGConformanceRecord] = []
        var withoutImage: [SVGConformanceRecord] = []
        var rows: [String] = []
        rows.reserveCapacity(records.count)

        for record in records {
            let ours = svgeeKitRepoRelativePath(for: record, repoRoot: repoRoot, fileManager: fileManager)
            let w3c = w3cReferenceRepoRelativePath(for: record.testId, repoRoot: repoRoot, fileManager: fileManager)
            if ours == nil && w3c == nil {
                withoutImage.append(record)
            } else {
                gallery.append(record)
                rows.append(galleryRow(record: record, ours: ours, w3c: w3c))
            }
        }

        var md = ""
        md += generatedMarker + "\n\n"
        md += "# \(tag)\n\n"
        md += "\(counts.total) tests · generated \(generatedOn) · [coverage index](README.md)\n\n"
        md += statusTable(counts)
        md += "\n"
        if counts.partialBaseline > 0 {
            md += "> `partialBaseline` means the render is tracked but **not** visually verified. "
            md += "Do not treat a matching partial snapshot as a pass.\n\n"
        }

        if !gallery.isEmpty {
            md += "## Renders\n\n"
            md += "| Test | Status | SVGeeKit | W3C reference |\n"
            md += "| --- | --- | --- | --- |\n"
            for row in rows {
                md += row
            }
            md += "\n"
        }

        if !withoutImage.isEmpty {
            md += "## No snapshot\n\n"
            md += "| Test | Status | Detail |\n"
            md += "| --- | --- | --- |\n"
            for record in withoutImage {
                md += noSnapshotRow(record)
            }
        }

        return md
    }

    static func galleryRow(
        record: SVGConformanceRecord,
        ours: String?,
        w3c: String?
    ) -> String {
        let source = docsRelative(svgRepoRelativePath(for: record.testId))
        let testCell = "[`\(record.testId)`](\(source))"
        let oursCell = imageCell(repoRelative: ours, alt: "SVGeeKit render of \(record.testId)")
        let w3cCell = imageCell(repoRelative: w3c, alt: "W3C reference for \(record.testId)")
        return "| \(testCell) | \(statusCell(record, includeDetail: true)) | \(oursCell) | \(w3cCell) |\n"
    }

    static func noSnapshotRow(_ record: SVGConformanceRecord) -> String {
        let source = docsRelative(svgRepoRelativePath(for: record.testId))
        let testCell = "[`\(record.testId)`](\(source))"
        let detail = escapeTable(record.detail ?? "")
        return "| \(testCell) | \(statusCell(record, includeDetail: false)) | \(detail) |\n"
    }

    static func imageCell(repoRelative: String?, alt: String) -> String {
        guard let repoRelative else { return "—" }
        let src = docsRelative(repoRelative)
        return "<img src=\"\(src)\" width=\"\(thumbnailWidth)\" alt=\"\(escapeHTML(alt))\">"
    }

    static func statusCell(_ record: SVGConformanceRecord, includeDetail: Bool) -> String {
        var cell = "`\(record.status.rawValue)`"
        if includeDetail, let detail = record.detail, !detail.isEmpty {
            cell += "<br>\(escapeHTML(detail))"
        }
        return cell
    }

    // MARK: - Paths

    static func chapterFileName(for tag: String) -> String {
        let allowed = CharacterSet.alphanumerics.union(CharacterSet(charactersIn: "-_"))
        let safe = String(tag.unicodeScalars.map { allowed.contains($0) ? Character($0) : "_" })
        return (safe.isEmpty ? "other" : safe) + ".md"
    }

    static func docsRelative(_ repoRelative: String) -> String {
        "../../\(repoRelative)"
    }

    static func svgRepoRelativePath(for testId: String) -> String {
        "Tests/SVGConformanceTests/Resources/W3C-SVG-1.1/svg/\(testId).svg"
    }

    static func svgeeKitRepoRelativePath(
        for record: SVGConformanceRecord,
        repoRoot: URL,
        fileManager: FileManager
    ) -> String? {
        let ordered: [String]
        switch record.status {
        case .partialBaseline:
            ordered = [
                partialSnapshotPath(testId: record.testId),
                verifiedSnapshotPath(testId: record.testId)
            ]
        default:
            ordered = [
                verifiedSnapshotPath(testId: record.testId),
                partialSnapshotPath(testId: record.testId)
            ]
        }
        return ordered.first { fileManager.fileExists(atPath: repoRoot.appending(path: $0).path) }
    }

    static func w3cReferenceRepoRelativePath(
        for testId: String,
        repoRoot: URL,
        fileManager: FileManager
    ) -> String? {
        let relative = "Tests/SVGConformanceTests/Resources/W3C-SVG-1.1/png/\(testId).png"
        guard fileManager.fileExists(atPath: repoRoot.appending(path: relative).path) else {
            return nil
        }
        return relative
    }

    static func verifiedSnapshotPath(testId: String) -> String {
        "Tests/__Snapshots__/\(testId)/baseline.png"
    }

    static func partialSnapshotPath(testId: String) -> String {
        "Tests/__PartialSnapshots__/\(testId)/baseline.png"
    }

    // MARK: - Counts & copy

    struct StatusCounts: Equatable {
        var passed = 0
        var partialBaseline = 0
        var failed = 0
        var skipped = 0
        var parseError = 0
        var renderError = 0
        var missingBaseline = 0

        var total: Int {
            passed + partialBaseline + failed + skipped + parseError + renderError + missingBaseline
        }

        var other: Int {
            failed + parseError + renderError + missingBaseline
        }

        init(_ records: [SVGConformanceRecord]) {
            for record in records {
                switch record.status {
                case .passed: passed += 1
                case .partialBaseline: partialBaseline += 1
                case .failed: failed += 1
                case .skipped: skipped += 1
                case .parseError: parseError += 1
                case .renderError: renderError += 1
                case .missingBaseline: missingBaseline += 1
                }
            }
        }
    }

    static func statusTable(_ counts: StatusCounts) -> String {
        var md = "| Status | Count |\n| --- | ---: |\n"
        md += "| `passed` | \(counts.passed) |\n"
        md += "| `partialBaseline` | \(counts.partialBaseline) |\n"
        md += "| `skipped` | \(counts.skipped) |\n"
        if counts.failed > 0 { md += "| `failed` | \(counts.failed) |\n" }
        if counts.parseError > 0 { md += "| `parseError` | \(counts.parseError) |\n" }
        if counts.renderError > 0 { md += "| `renderError` | \(counts.renderError) |\n" }
        if counts.missingBaseline > 0 { md += "| `missingBaseline` | \(counts.missingBaseline) |\n" }
        return md
    }

    static func statusLegend() -> String {
        """
        | Status | Meaning |
        | --- | --- |
        | `passed` | Render matches a human-verified baseline. |
        | `partialBaseline` | Render is captured and tracked, but **not** yet verified against the W3C pass criteria. |
        | `skipped` | Explicitly out of scope (`overrides.json`). |
        | `failed` | Diverged from a verified baseline. |
        | `parseError` / `renderError` | The test threw before a snapshot could be compared. |
        """
    }

    static func sortedTags(_ tags: [String]) -> [String] {
        let known = SVGFeatureTag.allCases.map(\.rawValue)
        let knownSet = Set(known)
        let orderedKnown = known.filter { tags.contains($0) }
        let extras = tags.filter { !knownSet.contains($0) }.sorted()
        return orderedKnown + extras
    }

    static func utcDayStamp(_ date: Date) -> String {
        date.formatted(
            Date.ISO8601FormatStyle(timeZone: TimeZone.gmt)
                .year()
                .month()
                .day()
                .dateSeparator(.dash)
        )
    }

    static func escapeHTML(_ string: String) -> String {
        string
            .replacingOccurrences(of: "&", with: "&amp;")
            .replacingOccurrences(of: "<", with: "&lt;")
            .replacingOccurrences(of: ">", with: "&gt;")
            .replacingOccurrences(of: "\"", with: "&quot;")
    }

    static func escapeTable(_ string: String) -> String {
        string.replacingOccurrences(of: "|", with: "\\|")
    }

    static func removeStaleGeneratedFiles(
        in directory: URL,
        keeping: Set<String>,
        fileManager: FileManager
    ) throws {
        let contents = try fileManager.contentsOfDirectory(
            at: directory,
            includingPropertiesForKeys: nil
        )
        for url in contents where url.pathExtension.lowercased() == "md" {
            let name = url.lastPathComponent
            guard !keeping.contains(name) else { continue }
            guard let firstLine = firstLine(of: url), firstLine.contains("SVGConformanceMarkdownReport") else {
                continue
            }
            try fileManager.removeItem(at: url)
        }
    }

    static func firstLine(of url: URL) -> String? {
        guard let handle = try? FileHandle(forReadingFrom: url) else { return nil }
        defer { try? handle.close() }
        let data = handle.readData(ofLength: 256)
        guard let text = String(data: data, encoding: .utf8) else { return nil }
        return text.split(separator: "\n", maxSplits: 1, omittingEmptySubsequences: false).first.map(String.init)
    }
}
